const courses = [
  {
    id: 1,
    name: "Introduction to React Native",
    shortDescription:
      "Learn the basics of React Native development and build your first mobile app.",
    image:
      "https://miro.medium.com/v2/resize:fit:1200/1*y6C4nSvy2Woe0m7bWEn4BA.png",
    instructor: "John Doe",
    specialty: "#ReactNativeBeginner",
    duration: "10 hours 15 minutes",
    totallecture: 25,
    location: "India",
    enrollmentStatus: "Open",
    expandable: [
      "Course Overview",
      "Syllabus",
      " Introduction to React Native",
      " Setting Up Environment",
      " Components and Props",
      " Styling in React Native",
      " Navigation and Routing",
      " State Management",
      " Handling User Input",
      " Networking",
      " Debugging and Testing",
      " Deployment",
    ],
    schedule: "Every Monday and Wednesday, 10:00 AM - 12:00 PM",
    Prerequisites:
      "Basic understanding of JavaScript and mobile app development",
    about: "",
    courseoutcome: [
      "👨‍🎤 Everything you need to be productive with React",
      "⚡ Breakdown of key concepts in 100 Seconds",
      "📚 Design patterns and best practices",
      "🎣 Component composition and custom hooks",
      "🚀 Lazy loading with Suspense",
      "📱 How to build Progressive Web Apps (PWAs)",
      "🎨 Animation with Framer Motion",
      "🐕 Advanced data fetching with SWR and React Query",
      "⚛️ Complex dynamic forms with React Final Form",
      "🔥 Manage realtime data with Firestore",
      "📰 SSR with Next.js",
      "🍰 More!",
    ],
    rating: 4,
    price: 999,
    enrolledstudents: 200,
    progress: 21,
  },
  {
    id: 2,
    name: "Advanced JavaScript",
    shortDescription:
      "Master advanced concepts of JavaScript programming language.",
    image:
      "https://www.pragimtech.com/wp-content/uploads/2019/03/java-script.jpg",
    instructor: "Jane Smith",
    specialty: "#advancejavascript",
    duration: "12 hours 26 minutes",
    totallecture: 32,
    location: "Online",
    enrollmentStatus: "Open",
    expandable: [
      "Course Overview",
      "Syllabus",
      " Advanced Functions",
      " Closures and Scope",
      " Prototypes and Inheritance",
      " Asynchronous JavaScript",
      " ES6+ Features",
      " Functional Programming",
      " Error Handling",
      " Design Patterns",
      " Testing and Debugging",
      " Performance Optimization",
    ],
    schedule: "Self-paced",
    Prerequisites: "Proficiency in basic JavaScript programming",
    courseoutcome: [
      "Understand advanced functions and closures in JavaScript",
      "Learn about prototypes and inheritance",
      "Explore asynchronous JavaScript and event loop",
      "Master ES6+ features and functional programming concepts",
      "Handle errors effectively and implement design patterns",
      "Write unit tests and debug JavaScript code",
      "Optimize performance of JavaScript applications",
    ],
    rating: 4.2,
    price: 599,
    enrolledstudents: 240,
    progress: 50,
  },
  {
    id: 3,
    name: "Data Science Fundamentals",
    shortDescription: "Explore the fundamentals of data science and analytics.",
    image:
      "https://cdn5.vectorstock.com/i/1000x1000/11/94/data-science-logo-icon-design-vector-17661194.jpg",
    instructor: "Alice Johnson",
    specialty: "#DataScience",
    duration: "8 hours 50 minutes",
    totallecture: 36,
    location: "Online",
    enrollmentStatus: "pending",
    expandable: [
      "Course Overview",
      "Syllabus",
      " Introduction to Data Science",
      " Data Preprocessing",
      " Exploratory Data Analysis",
      " Data Visualization",
      " Introduction to Machine Learning",
      " Supervised Learning",
      " Unsupervised Learning",
      " Model Evaluation and Selection",
    ],
    schedule: "Every Tuesday and Thursday, 6:00 PM - 8:00 PM",
    Prerequisites: "Basic understanding of mathematics and statistics",
    courseoutcome: [
      "Understand the fundamentals of data science",
      "Preprocess data for analysis",
      "Explore data using statistical and visualization techniques",
      "Apply machine learning algorithms for predictive modeling",
      "Evaluate and select the best models for given data",
    ],
    rating: 4.2,
    price: 799,
    enrolledstudents: 150,
    progress: 82,
  },
  {
    id: 4,
    name: "Python for Beginners",
    shortDescription:
      "Get started with Python programming language from scratch.",
    image:
      "https://images.datacamp.com/image/upload/f_auto,q_auto:best/v1603718736/Why_Your_Company_Needs_Python_for_Business_Analytics_xzzles.png",
    instructor: "David Smith",
    specialty: "#PythonBeginner",
    duration: "6 hours 25 minutes",
    totallecture: 26,
    location: "Online",
    enrollmentStatus: "Closed",
    expandable: [
      "Course Overview",
      "Syllabus",
      " Introduction to Python",
      " Data Types and Variables",
      " Control Flow and Loops",
      " Functions",
      " Data Structures",
      " Introduction to OOP",
    ],
    schedule: "",
    Prerequisites: "None",
    courseoutcome: [
      "Learn the basics of Python programming language",
      "Understand different data types and variables in Python",
      "Master control flow and loop structures in Python",
      "Write functions and understand the concept of scope",
      "Explore different data structures in Python",
      "Get introduced to Object-Oriented Programming (OOP) in Python",
    ],
    rating: 4.3,
    price: 1299,
    enrolledstudents: 176,
    progress: 36,
  },
  {
    id: 5,
    name: "Web Development Bootcamp",
    shortDescription:
      "Join our intensive bootcamp to become a full-stack web developer.",
    image:
      "https://miro.medium.com/v2/resize:fit:1200/1*V-Jp13LvtVc2IiY2fp4qYw.jpeg",
    instructor: "Sarah Johnson",
    specialty: "#FullStackBootcamp",
    duration: "16 hours 35 minutes",
    totallecture: 45,
    location: "Online",
    enrollmentStatus: "Open",
    expandable: [
      "Course Overview",
      "Syllabus",
      " HTML and CSS Basics",
      " Intermediate HTML and CSS",
      " JavaScript Fundamentals",
      " Advanced JavaScript and DOM Manipulation",
      " Backend Development with Node.js",
      "  Database Management with MongoDB",
      "  Express.js and RESTful APIs",
      "  Frontend Frameworks (React, Angular, Vue)",
      " Project Phase - Full-Stack Development",
      "  Deployment and Hosting",
      " Continuous Integration and Deployment",
      "  Project Presentations and Review",
    ],
    schedule: "Every Saturday and Sunday, 9:00 AM - 5:00 PM",
    Prerequisites: "Basic knowledge of HTML, CSS, and JavaScript",
    courseoutcome: [
      "Understand the basics of HTML and CSS",
      "Learn intermediate and advanced HTML and CSS techniques",
      "Master fundamental JavaScript concepts",
      "Explore advanced JavaScript and DOM manipulation",
      "Build backend applications with Node.js",
      "Manage databases using MongoDB",
      "Create RESTful APIs with Express.js",
      "Get introduced to popular frontend frameworks like React, Angular, and Vue",
      "Develop full-stack web applications",
      "Deploy web applications and implement continuous integration and deployment",
      "Present and review projects",
    ],
    rating: 4.6,
    price: 1299,
    enrolledstudents: 100,
    progress: 74,
  },
  {
    id: 6,
    name: "Machine Learning Basics",
    shortDescription:
      "Learn the basics of machine learning algorithms and applications.",
    image:
      "https://www.fsm.ac.in/blog/wp-content/uploads/2022/08/ml-e1610553826718.jpg",
    instructor: "Michael Brown",
    specialty: "#MachineLearning101",
    duration: "10 hours 45 minutes",
    totallecture: 26,
    location: "Online",
    enrollmentStatus: "Open",
    expandable: [
      "Course Overview",
      "Syllabus",
      "  Introduction to Machine Learning",
      " Linear Regression",
      "  Logistic Regression",
      "  Decision Trees and Random Forests",
      "  Support Vector Machines (SVM)",
      "  Clustering Algorithms",
      "  Dimensionality Reduction Techniques",
      "  Neural Networks and Deep Learning",
      "  Reinforcement Learning",
      "  Applications and Case Studies",
    ],
    schedule: "Every Monday and Wednesday, 6:00 PM - 8:00 PM",
    Prerequisites: "Basic understanding of Python and mathematics",
    courseoutcome: [
      "Understand the fundamentals of machine learning",
      "Implement linear and logistic regression algorithms",
      "Explore decision trees and random forests",
      "Learn about support vector machines (SVM)",
      "Understand clustering algorithms",
      "Apply dimensionality reduction techniques",
      "Build neural networks and understand deep learning",
      "Explore reinforcement learning",
      "Understand the applications of machine learning in real-world case studies",
    ],
    rating: 4.5,
    price: 999,
    enrolledstudents: 240,
    progress: 20,
  },
  {
    id: 7,
    name: "Digital Marketing Strategies",
    shortDescription:
      "Explore effective digital marketing strategies for businesses.",
    image:
      "https://www.simplilearn.com/ice9/free_resources_article_thumb/What_is_digital_marketing.jpg",
    instructor: "Emily Johnson",
    specialty: "#DigitalMarketingPro",
    duration: "8 hours 38 minutes",
    totallecture: 16,
    location: "Online",
    enrollmentStatus: "closed",
    expandable: [
      "Course Overview",
      "Syllabus",
      "  Introduction to Digital Marketing",
      "  Content Marketing",
      "  Search Engine Optimization (SEO)",
      "  Search Engine Marketing (SEM)",
      "  Social Media Marketing (SMM)",
      "  Email Marketing",
      "  Web Analytics",
      "  Digital Marketing Strategy and Planning",
    ],
    schedule: "Every Tuesday and Thursday, 8:00 PM - 10:00 PM",
    Prerequisites: "None",
    courseoutcome: [
      "Understand the basics of digital marketing",
      "Implement content marketing strategies",
      "Optimize websites for search engines (SEO)",
      "Utilize search engine marketing (SEM) techniques",
      "Leverage social media platforms for marketing purposes",
      "Implement email marketing campaigns",
      "Analyze website traffic and user behavior using web analytics tools",
      "Develop digital marketing strategies and plans",
    ],
    rating: 3.8,
    price: 1099,
    enrolledstudents: 236,
    progress: 60,
  },
  {
    id: 8,
    name: "Mobile App Design",
    shortDescription: "Design engaging and user-friendly mobile applications.",
    image:
      "https://freedesignfile.com/upload/2017/12/Mobile-app-logo-vector.jpg",
    instructor: "Mark Taylor",
    specialty: "#AppDesignTrends",
    duration: "8 hours 47 minutes",
    totallecture: 14,
    location: "Online",
    enrollmentStatus: "Open",
    expandable: [
      "Course Overview",
      "Syllabus",
      "  Introduction to Mobile App Design",
      "  UI/UX Principles",
      "  Wireframing and Prototyping",
      "  Designing for Different Platforms (iOS, Android)",
      "  Responsive Design",
      "  Animation and Interaction Design",
      "  Usability Testing",
      "  App Design Trends and Case Studies",
    ],
    schedule: "Every Wednesday and Friday, 2:00 PM - 4:00 PM",
    Prerequisites: "Basic knowledge of graphic design principles",
    courseoutcome: [
      "Understand the principles of mobile app design",
      "Design user interfaces (UI) and user experiences (UX)",
      "Create wireframes and prototypes for mobile apps",
      "Design for different mobile platforms (iOS, Android)",
      "Implement responsive design techniques",
      "Incorporate animations and interactions into mobile app designs",
      "Conduct usability testing to improve user experience",
      "Stay updated on app design trends and case studies",
    ],
    rating: 3.9,
    price: 899,
    enrolledstudents: 185,
    progress: 80,
  },
  {
    id: 9,
    name: "Cybersecurity Fundamentals",
    shortDescription:
      "Learn the basics of cybersecurity and protect against threats.",
    image:
      "https://imageio.forbes.com/specials-images/imageserve/642445004586b4330e81b689//960x0.jpg?height=406&width=711&fit=bounds",
    instructor: "Sophia Miller",
    specialty: "#CybersecurityEssentials",
    duration: "10 hours 20 minutes",
    totallecture: 27,
    location: "Online",
    enrollmentStatus: "pending",
    expandable: [
      "Course Overview",
      "Syllabus",
      "  Introduction to Cybersecurity",
      "  Network Security",
      "  Cryptography",
      "  Access Control and Identity Management",
      "  Threat Detection and Prevention",
      "  Incident Response and Recovery",
      "  Security Assessment and Auditing",
      "  Ethical Hacking and Penetration Testing",
      "  Cybersecurity Best Practices",
      "  Emerging Trends in Cybersecurity",
    ],
    schedule: "Every Monday and Wednesday, 8:00 PM - 10:00 PM",
    Prerequisites:
      "Basic understanding of computer networks and operating systems",
    courseoutcome: [
      "Understand the fundamentals of cybersecurity",
      "Implement network security measures",
      "Apply cryptographic techniques for data protection",
      "Manage access control and identity management systems",
      "Detect and prevent cybersecurity threats",
      "Respond to and recover from cybersecurity incidents",
      "Conduct security assessment and auditing",
      "Explore ethical hacking and penetration testing",
      "Implement cybersecurity best practices",
      "Stay updated on emerging trends in cybersecurity",
    ],
    rating: 4.2,
    price: 700,
    enrolledstudents: 290,
    progress: 33,
  },
  {
    id: 10,
    name: "Blockchain Essentials",
    shortDescription:
      "Explore the fundamentals of blockchain technology and cryptocurrencies.",
    image:
      "https://futureskillsprime.in//sites/default/files/2022-02/Link%20Sharing_1200x630_%20Blockchain%20Essentials.jpg",
    instructor: "Andrew Thompson",
    specialty: "#BlockchainBasics",
    duration: "8 hours 35 minutes",
    totallecture: 16,
    location: "Online",
    enrollmentStatus: "Open",
    expandable: [
      "Course Overview",
      "Syllabus",
      "  Introduction to Blockchain",
      "  Cryptocurrency Basics",
      "  Blockchain Networks and Consensus Mechanisms",
      "  Smart Contracts",
      "  Decentralized Applications (DApps)",
      "  Blockchain Security",
      "  Regulatory and Legal Considerations",
      "  Blockchain Use Cases and Applications",
    ],
    schedule: "Every Tuesday and Thursday, 6:00 PM - 8:00 PM",
    Prerequisites: "Basic understanding of computer science",
    courseoutcome: [
      "Understand the fundamentals of blockchain technology",
      "Learn about cryptocurrencies and their underlying technology",
      "Explore blockchain networks and consensus mechanisms",
      "Understand smart contracts and decentralized applications (DApps)",
      "Learn about blockchain security measures",
      "Explore regulatory and legal considerations in blockchain",
      "Discover various blockchain use cases and applications",
    ],
    rating: 4.8,
    price: 1199,
    enrolledstudents: 90,
    progress: 45,
  },
];

export default courses;
